### ISSUE TITLE
移植Chrome : popup显示样式

### ISSUE THREAD

**Issue by bsplu** [c4rO-0/YouTube-Filter#4]
popup侧边显示多个滑条
![default](https://user-images.githubusercontent.com/6471567/36561179-41004c6c-1813-11e8-878b-378bf3b18443.png)

**Comment by l365692902** [comment]
google习惯性留白边。。。导致600像素的高度实际上只有584可以用，一旦超过就会出现chrome自己添加的滚动条。另外chrome和firefox环境中字体的默认大小不同，导致这里的字体相比较与firefox中要大。现在已经修改成相对于像素值的大小，字体大小不再依赖环境。顺便修复了两行文字不连贯的问题
